server:
  port: 9000

logging:
  level:
    org: info
    com: off

spring:
  mvc:
    static-path-pattern: /static/**
---

spring:
  profiles:
    active: local

# Local profile configuration
---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:data
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: false
    show-sql: true


# Production profile configuration
---
spring:
  config:
    activate:
      on-profile: prod
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema-postgres.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  logging:
    level:
      org: info
      com: off
